name: Jest (mobile)
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Enters directory
      run: cd packages/mobile
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
